Develop fix
tomlogan501/robosense_simulator pull request #1
Opened 2022-03-25 07:55 UTC by deepinbubblegum

2022-03-25 09:06 UTC, tomlogan501 commented
Can you switch to develop ? I create it for futures minor changes like that

2023-03-02 16:01 UTC, rokusottervanger commented
What's the status on this? Can this be merged?

2023-03-02 17:55 UTC, tomlogan501 requested changes

2023-03-02 17:55 UTC, tomlogan501 commented on .gitignore
> +.vscode
I don't want to add because other IDE can be used and everyone want to add to the gitignore

2023-03-02 17:55 UTC, tomlogan501 commented on robosense_description/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.2)
ok for the upgrade

2023-06-22 09:46 UTC, tomlogan501 commented
Friendly ping

2023-06-22 10:19 UTC, rokusottervanger commented
I believe the example is already fixed by #2. I'm not sure why the CMake required version should be increased to 3.0.2?

2023-12-14 09:59 UTC, closed without merging